pipeline:
  name: "test-cancel-pipeline"

stages:
  - build
  - test
  - deploy

jobs:
  - name: "job-a"
    stage: "build"
    image: "alpine:latest"
    script:
      - "echo 'This job fails intentionally'"
      - "false"
    allow_failure: false

  - name: "job-b"
    stage: "test"
    image: "alpine:latest"
    needs:
      - "job-a"
    script:
      - "echo 'Job B should be canceled'"
    allow_failure: true

  - name: "job-c"
    stage: "test"
    image: "alpine:latest"
    needs:
      - "job-a"
    script:
      - "echo 'Job C should also be canceled'"
    allow_failure: true

  - name: "job-d"
    stage: "deploy"
    image: "alpine:latest"
    needs:
      - "job-b"
      - "job-c"
    script:
      - "echo 'Job D should be canceled because B and C are canceled'"
    allow_failure: true
